pub mod bool_to_word;
pub mod calculate_bmi;
pub mod ease_the_stock_broker;
pub mod errors_histogram;
pub mod find_the_parity_outlier;
pub mod get_the_middle_character;
pub mod who_likes_it;
pub mod word_spinner;
pub mod your_order_please;
